apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nlanzl0qr-nodejs 
  janus-idp.io/tekton: nlanzl0qr-nodejs
  backstage.io/kubernetes-id: nlanzl0qr-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nlanzl0qr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml