apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nlanzl0qr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nlanzl0qr-nodejs 
  name: nlanzl0qr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nlanzl0qr-nodejs 
